# Elansol Developers Guide Configuration

site_name: Elansol Developers Guide
site_url: https://squidfunk.github.io/mkdocs-material/
# Define the navigation structure for the documentation
nav:
  - "<h4 style='margin: 0; padding: 0;'>ğŸ  Home</h4>": index.md # The homepage of the guide
  - "<h4 style='margin: 0; padding: 0;'>ğŸ”  Naming Conventions</h4>": namingConventions.md # Guide to naming conventions
  - "<h4 style='margin: 0; padding: 0;'>ğŸ¨ Frontend Guide</h4>": frontendGuide.md # Frontend development guidelines
  - "<h4 style='margin: 0; padding: 0;'>âš™ï¸ Backend Guide</h4>": backendGuide.md # Backend development guidelines
  - "<h4 style='margin: 0; padding: 0;'>âš¡ Electron Guide</h4>": electronGuide.md # Electron development guidelines
  - "<h4 style='margin: 0; padding: 0;'>âš›ï¸ React Crash Course</h4>": reactCrashCourse.md # React crash course
  - "<h4 style='margin: 0; padding: 0;'>ğŸ–¥ï¸ Nodejs and Express Crash Course</h4>": nodeAndExpressCrashCourse.md # Node.js and Express crash course

theme:
  name: material
